#!/usr/bin/env bash

function die () {
  cat <<__EOF__

  Error:

__EOF__

  exit 1
}
set -x
mkdir -p /srv/
ls /srv/dvwa || git clone --branch dvwa https://github.com/galaxy3-net/dvwa.git /srv/dvwa
(cd /srv/dvwa && git pull)

cp /srv/splunk/usr/sbin/dvwa /usr/sbin/dvwa
chown root:root /usr/sbin/dvwa
chmod 0700 /usr/sbin/dvwa
cp /srv/splunk/etc/supervisor/conf.d/dvwa.conf /etc/supervisor/conf.d/dvwa.conf
chown root:root /etc/supervisor/conf.d/dvwa.conf
chmod 0400 /etc/supervisor/conf.d/dvwa.conf

supervisorctl reread
supervisorctl update


