#!/usr/bin/env bash

#exec | tee -a /var/log/named_startup.log
#exec 2>&1

CONTAINER_NAME=dvwa
CONTAINER_IMAGE=vulnerables/web-dvwa:latest

function start () {
    docker pull ${CONTAINER_IMAGE}
	sudo -E docker run -t --entrypoint "/bin/sh" --name ${CONTAINER_NAME} \
		-p 10.55.56.10:80:80/tcp \
		${CONTAINER_IMAGE} || sudo docker start -a -i ${CONTAINER_NAME}
}

case ${1} in

	start)
		docker || apt install -y docker docker.io
		docker info || (systemctl start docker ; sleep 300)
		start
		;;

	stop)
		docker stop ${CONTAINER_NAME} || echo "${CONTAINER_NAME} not running"
		;;

	rm)
		docker stop ${CONTAINER_NAME} || echo "${CONTAINER_NAME} not running"
		docker rm ${CONTAINER_NAME} || echo "${CONTAINER_NAME} doesn't exist"
		;;

	*)
		echo "Usage: ${1} [start | stop | rm]"
		;;
esac
