#!/usr/bin/env bash

#exec | tee -a /var/log/named_startup.log
#exec 2>&1

CONTAINER_NAME=dvwa
CONTAINER_IMAGE=vulnerables/web-dvwa:latest

function start () {
    docker pull ${CONTAINER_IMAGE}
	sudo -E docker run -d -t --entrypoint "/bin/sh" --name ${CONTAINER_NAME} \
		-p 10.55.56.10:80:80/tcp \
		${CONTAINER_IMAGE} || sudo docker start ${CONTAINER_NAME}
}

docker || apt install -y docker docker.io
docker info || systemctl start docker

start

